version: '3'
   
services:
  web:
    build: .
    command: sh -c "python3 manage.py migrate && gunicorn goalstack.wsgi --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=*
